language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
  script:
    - ./gradlew clean test
notifications:
  email: false
  slack: kotaishimoto:mnkx14uWrYj3KKKXPOJT40dy
