language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    # Emulator Management: Create, Start and Wait
    before_script:
      - echo yes | android create avd --force -n test -t android-22 --abi x86
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
  script:
    - ./gradlew clean test
notifications:
  email: false
  slack: kotaishimoto:mnkx14uWrYj3KKKXPOJT40dy
